// furichess v1
#include <stdio.h>

enum Piece {
    ROOK,
    KNIGHT,
    BISHOP,
    QUEEN,
    KING,
    PAWN,
    NO_PIECE
};

enum Color {
    BLACK,
    WHITE,
    NO_COLOR
};

int pieces[64] = {
    ROOK,  KNIGHT, BISHOP, QUEEN, KING,  BISHOP, KNIGHT, ROOK,
    PAWN,  PAWN,   PAWN,   PAWN,  PAWN,  PAWN,  PAWN,   PAWN,
    NO_PIECE, NO_PIECE, NO_PIECE, NO_PIECE,
    NO_PIECE, NO_PIECE, NO_PIECE, NO_PIECE,
    NO_PIECE, NO_PIECE, NO_PIECE, NO_PIECE,
    NO_PIECE, NO_PIECE, NO_PIECE, NO_PIECE,
    NO_PIECE, NO_PIECE, NO_PIECE, NO_PIECE,
    NO_PIECE, NO_PIECE, NO_PIECE, NO_PIECE,
    NO_PIECE, NO_PIECE, NO_PIECE, NO_PIECE,
    NO_PIECE, NO_PIECE, NO_PIECE, NO_PIECE,
    PAWN,  PAWN,   PAWN,   PAWN,  PAWN,  PAWN,  PAWN,   PAWN,
    ROOK,  KNIGHT, BISHOP, QUEEN, KING,  BISHOP, KNIGHT, ROOK
};

int colors[64] = {
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK,
    NO_COLOR, NO_COLOR, NO_COLOR, NO_COLOR,
    NO_COLOR, NO_COLOR, NO_COLOR, NO_COLOR,
    NO_COLOR, NO_COLOR, NO_COLOR, NO_COLOR,
    NO_COLOR, NO_COLOR, NO_COLOR, NO_COLOR,
    NO_COLOR, NO_COLOR, NO_COLOR, NO_COLOR,
    NO_COLOR, NO_COLOR, NO_COLOR, NO_COLOR,
    NO_COLOR, NO_COLOR, NO_COLOR, NO_COLOR,
    NO_COLOR, NO_COLOR, NO_COLOR, NO_COLOR,
    WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
    WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE
};

int main() {
    return 0;
}
